### library
```{r}
library(torch)
library(tidyverse)
```

### dataset
```{r}
df= iris %>% filter(Species %in% c("setosa","versicolor"))

df=
  df %>% 
  mutate(Species= factor(Species, 
                         levels = c("setosa","versicolor"),
                         labels = c(0,1)))
df
```
### tensor (data & label)
```{r}
(X.tensor= df[1:4] %>% as.matrix() %>% torch_tensor(.))
(Y.tensor= df$Species %>% as.character() %>% 
    as.numeric() %>% as.matrix() %>% torch_tensor(.))
```


### model, loss.function, optimizer
```{r}
model= nn_linear(in_features = 4, out_features = 1, bias = F)
loss.f= nn_bce_with_logits_loss()
optimizer= optim_sgd(model$parameters, lr=0.25)
```

### training
```{r}
losses= vector()

for (i in 1:100){
  optimizer$zero_grad()
  y_pred= model(X.tensor)
  loss= loss.f(y_pred, Y.tensor)
  loss$backward()
  optimizer$step()
  
  losses= c(losses, loss %>% as_array(.))
}
```

```{r}
tibble(
  No= seq(1,100),
  loss= losses) %>% 
  ggplot(aes(x=No, y=loss))+geom_path(size=0.2, color="red")
```

```{r}
losses
```














